language: java
jdk:
  - oraclejdk8

addons:
  sonarqube:
    organization: rainerhahnekamp-github
    token:
      secure: 4e891e5de78c822bce4d9c2da399fcb017183316

before_script:
  - npm install -g angular-cli@1.0.0

script:
  - ./gradlew sonarqube
  - ng lint

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
    - 'node_modules'
  yarn: true
