language: node_js
dist: trusty

services:
  - docker

addons:
  sonarcloud:
    organization: rainerhahnekamp-github
    token:
      secure: 4e891e5de78c822bce4d9c2da399fcb017183316

before_install:
  - docker run -it -u `id -u $USER` --rm -v $PWD:/app -w /app node:8.9.3 yarn --cache-folder /app/.yarn-cache
  - docker run -it -u `id -u $USER` --rm -v $PWD:/app -w /app node:8.9.3 npm run ci
  - sudo apt-get install oracle-java8-set-default
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle

before_script:
  - echo $JAVA_HOME
  - ./gradlew assemble

script:
  - ./gradlew check
  - ./gradlew sonarqube


before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.yarn-cache'
    - 'node_modules'
