language: node_js

addons:
  apt:
    packages:
      - oracle-java8-set-default
  sonarqube:
    organization: rainerhahnekamp-github
    token:
      secure: 4e891e5de78c822bce4d9c2da399fcb017183316

before_script:
  - echo $JAVA_HOME
  - npm install -g @angular/cli@1.0.0
  - ./gradlew assemble

script:
  - ./gradlew check
  - ng lint


before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - 'node_modules'
  yarn: true
