language: java
dist: trusty

services:
  - docker

addons:
  sonarcloud:
    organization: rainerhahnekamp-github
    token:
      secure: 4e891e5de78c822bce4d9c2da399fcb017183316

before_install:
  - docker run -it --rm -v $PWD:/app -w /app node:8.9.4 yarn --cache-folder /app/.yarn-cache
  - docker run -it -u `id -u $USER` --rm -v $PWD:/app -w /app node:8.9.4 npm run ci

script:
  - echo $JAVA_HOME
  - ./mvnw verify


cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '.yarn-cache'
    - 'node_modules'
