logging:
  level:
    org.springframework.security: DEBUG

lombok:
  log:
    fieldIsStatic: false

mail:
  smtpServer: localhost
  login: none
  password: none
  defaultSender: someemail@somehost.com
